module.exports = {
  analytics: require('./analytics')
, api: require('./api')
, auth: require('./auth')
, contactUs: require('./contact-us')
, emails: require('./emails')
, items: require('./items')
, orders: require('./orders')
, paymentSummaries: require('./payment-summaries')
, reports: require('./reports')
, restaurants: require('./restaurants')
, session: require('./session')
, statics: require('./statics')
, users: require('./users')
, waitlist: require('./waitlist')
, admin: require('./admin')
}
