module.exports = {
  cors: require('./cors')
, domains: require('./domains')
, uuid: require('./uuid')
, sslRedirect: require('./ssl-redirect')
, requestLogger: require('connect-request-logger-pg')
, getUser: require('./get-user')
, statusCodeIntercept: require('./status-code-intercept')
, setSession: require('./set-session')
, analytics: require('./analytics')
, orderParams: require('./order-params')
, restrict: require('./restrict')
, basicAuth: require('./basic-session-auth')
, buildReceipt: require('./build-receipt')
, queryParams: require('./query-params')
, queryString: require('./query-string')
, restaurant: require('./restaurant')
, after: require('./after')
};
